apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: circleci-server
  namespace: argocd
  labels:
    visibility: hidden
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: cciserver.azurecr.io
      targetRevision: {{ index .Values "circleci-server-version" | quote }}
      chart: circleci-server
      helm:
        valueFiles:
        - $values/k8s/applications/values.yaml
    - repoURL: {{ .Values.argocd.repository }}
      targetRevision: main
      ref: values
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: circleci-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true