apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevpn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kubevpn
  source:
    repoURL: https://raw.githubusercontent.com/kubenetworks/kubevpn/master/charts
    targetRevision: 2.9.11
    chart: kubevpn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true