apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    chart: telepresence
    repoURL: https://app.getambassador.io
    targetRevision: 2.20.2
    helm:
      releaseName: traffic-manager
      values: |
        managerRbac:
          create: true
          namespaced: false
        licenseKey:
          create: false
        client:
          connectionTTL: 24h
        logLevel: info
        agent:
          logLevel: info
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true