apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telepresence
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    chart: telepresence
    repoURL: https://app.getambassador.io
    targetRevision: 2.20.2
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  